services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SERVICE_NAME: microservice-template
      LOG_LEVEL: info
      EVENT_BUS_DRIVER: memory
